
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_SIGN_UP = 'AUTH_CREATE'
export const AUTH_SIGN_UP_FAIL = 'AUTH_CREATE_FAIL'
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_CREATE_SUCCESS'