
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL'
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS'